spring.application.name=gastrohub

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/techchallenge}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

server.error.include-message=always
server.error.include-binding-errors=always

spring.jackson.default-property-inclusion=non_null

logging.level.br.com.gastrohub=DEBUG
logging.level.org.springframework.web=DEBUG

jwt.segredo=${JWT_SEGREDO:gastrohub-fiap-postech-chave-secreta-segura-256-bits-minimo}
jwt.expiracao-em-minutos=30
