# Configurações da aplicação
spring.application.name=gastrohub

# Datasource PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/techchallenge}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta da aplicação
server.port=8080

# Mensagens de erro detalhadas
server.error.include-message=always
server.error.include-binding-errors=always

# Ignorar campos nulos nas respostas JSON
spring.jackson.default-property-inclusion=non_null

# Logging
logging.level.br.com.gastrohub=DEBUG
logging.level.org.springframework.web=DEBUG

# JWT
jwt.segredo=${JWT_SEGREDO:gastrohub-fiap-postech-chave-secreta-segura-256-bits-minimo}
jwt.expiracao-em-minutos=30
